ports:
  - port: 5000
    onOpen: open-preview

tasks:
  - name: Start Redis Stack
    init: |
     docker-compose pull
    command: |
     alias redis-cli="docker exec -it redis-stack redis-cli" 
     echo "Use redis-cli to interact with Redis here."
     docker-compose up -d
     gp sync-done finished
    openMode: split-left
  - name: Start Flask Application
    init: |
      export FLASK_ENV=development
      pip install -r requirements.txt
    command: |
      gp sync-await finished && \
      flask run
    openMode: split-right

vscode:
  extensions:
    - ms-python.python
